version: "3.8"
services:
  stock-management:
    build: .
    restart: always
    ports:
      - 8081:8080
    depends_on:
       - mysqldb
  mysqldb:
    image : mysql
    restart: always
    ports :
      - 3307:3306
    environment:
       MYSQL_DATABASE: stock-management-dev
       MYSQL_USER: root
       MYSQL_PASSWORD :
       MYSQL_ROOT_PASSWORD :





