

spring:
  profiles:
    active : dev
---
spring:
  profiles: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/stock-management-dev
    password:
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
---
spring:
  profiles: prod
  datasource:
    username: root
    url: jdbc:mysql://mysqldb:3306/stock-management
    password:
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: none




